name: InsightCloudSec Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  ics-scan-and-upload:
    name: insightCloudSec repository scan with Github Advanced Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run InsightCloudSec Scan
        uses: rapid7/insightcloudsec-actions@v2.0.1
        with:
          api_key: ${{ secrets.ICS_API_KEY }}
          ics_base_url: ${{ secrets.ICS_BASE_URL }}
          config_name: AWS CIS Benchmark 1.4
          # directory: ./src   # <-- opcjonalnie: folder do skanowania
          # fail_on_severity: high   # <-- opcjonalnie: zatrzymuj workflow na high vulnerabilities
          # ics_base_url: https://twoj-serwer.example.com   # <-- opcjonalnie: jeśli masz on-prem
      - name: Attach scan artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mimics-scan-artifacts
          path: |
            ./log/mimics*.log
            ./ics_scan.
      - name: Upload Scan Results (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: results/
