---
name: "Github Actions ICS Demo"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  terraform-plan-generation:
    name: Terraform Plan Generation 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: modules/module-1

      - name: Terraform Plan
        id: plan
        run: terraform plan -out out.plan
        working-directory: modules/module-1
        
      - name: Show And Save Terraform JSON Output 
        id: show
        run: terraform show -json out.plan > out.plan.json
        working-directory: modules/module-1

      - name: Save And Archive Json Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-json
          path: modules/module-1/out.plan.json
  
  ics-scanner:
    name: ICS Terraform Scan
    needs: terraform-plan-generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve the TF Plan Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: terraform-plan-json
          path: .

      - name: Scan the TF plan
        uses: rapid7/insightcloudsec-actions@v2
        with:
          api_key: ${{ secrets.ics_api_key }}
          base_url: ${{ secrets.ics_base_url }}
          config_name: Demo IaC Configuration
          target: out.plan.json

      - name: Attach scan artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ICS-scan-artifacts
          path: |
            log/
            ics_scan.*
