name: InsightCloudSec Scan
uses: rapid7/insightcloudsec-actions@v2.0.1
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run InsightCloudSec Scan
        uses: rapid7/insightcloudsec-scan-action@master
        with:
          api_key: ${{ secrets.ICS_API_KEY }}
          ics_base_url: ${{ secrets.ICS_BASE_URL }}
